name: Provera kazni

on:
  schedule:
    - cron: "0 12 * * *"   # svakog dana u 12:00
  workflow_dispatch:        # ruƒçno pokretanje

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install node-fetch@3

      - name: Run script
        env:
          PNS_USER: ${{ secrets.PNS_USER }}
          PNS_PASS: ${{ secrets.PNS_PASS }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: node check.js
